### ISSUE TITLE
Density calculation error?

### ISSUE THREAD

**Issue by auersteve** [williamgravel/aerospace-toolbox#1]
I started looking at results from your 1976 Standard Atmosphere model, and noticed a discrepancy in the density calculation, when comparing your code results to data from the NASA Standard Atmosphere document you reference. I noticed this when I needed to calculate the derivative of density with respect to altitude. The discrepancy starts at 11 km. Below are data from your code and from the NASA document. Note that they agree to the 5 significant figures shown in the NASA document for Z = 10.8 km and 10.9 km, but differ for 11.0 km and greater altitudes.

 Z(km)      rho(your code)  rho( document)
  10.8000    0.37417                  .37417
  10.9000    0.36946                .36946
  11.0000     0.36480                .36392
  11.1000     0.35931                 .35822
  11.2000     0.35371                 .35262

You can see this most easily in the attached plot of the derivative of density with respect to altitude, created using data from your code. Note the jump in the derivative at 
[Derivative of Density.pdf](https://github.com/williamgravel/aerospace-toolbox/files/7414123/Derivative.of.Density.pdf)

**Comment by williamgravel** [comment]
Hey Steven, there are a few factors at play here for the differences you've observed.

First, the appendices in the NASA document include tables dependent on geopotential altitude (`H`) and geometric altitude (`Z`), with these tables alternating between the two altitude reference frames. The values you provided for 10.8-10.9 km were taken from the geometric altitude table (page 57), while the values for 11.0-11.2 km were taken from the geopotential altitude table (page 58, very next page). I've included a table showing the differences below, which my code should be able to recreate (although I will update the MATLAB File Exchange submission just in case I've updated something and forgot to push changes).

| Altitude [km] | Density w.r.t. Geopotential Altitude [kg/m^3] | Density w.r.t. Geometric Altitude [kg/m^3] |
| --- | --- | --- |
| 10.6 | 3.8287 | 3.8372 |
| 10.7 | 3.7806 | 3.7892 |
| 10.8 | 3.7330 | 3.7417 |
| 10.9 | 3.6859 | 3.6946 |
| 11.0 | 3.6392 | 3.6480 |
| 11.1 | 3.5822 | 3.5932 |
| 11.2 | 3.5262 | 3.5372 |

Second, the sudden change in the density derivative at around H = 11 km is most likely due to the change in the definition of the atmospheric layers and reference gradients. In other words, the U.S. Standard Atmosphere Model defines _boundary layers_ with different temperature gradients, one of which is found at H = 11 km (see figure below).

![image](https://user-images.githubusercontent.com/36943873/147295333-3631ed9e-ed63-4730-9089-bccc5f114425.png)

I hope this helps and clears up some of these discrepancies. Let me know if something bizarre is still taking place.

**Comment by auersteve** [comment]
William,

Thanks for your reply. I agree that my comments were incorrect, and that the cause was - as you pointed out - that I didn't realize that the data for geometric and geopotential altitude are on alternating pages of the U.S. Standard Atmosphere document.

I also agree (and indeed I knew) that 11 km is a boundary. However,  I thought that the reason for the discontinuous derivative of density at the 11 km boundary was an error in your code; now I realize that the reason is that the underlying 1976 Standard Atmosphere model gives a discontinuous derivative at the boundary.

I note that your file testStandardAtmos.m has one minor error: line 5 reads 
Results = StandardAtmos(1000,'HeightUnit','km','OutputFormat','Struct');
Your argument validation statements - specifically line 32 of StandardAtmos.m - is 
opts.OutputFormat (1,1) string {mustBeMember(opts.OutputFormat,{'table','struct'})} = 'table'
which catches the fact that 'Struct' is not an allowed string (whereas 'struct' is allowed)

One final comment about your code: I have access to the MATLAB Aerospace Toolbox, and I compared the density calculated by your code to the density calculated by toolbox function atmoscoesa.m. For your information, I have attached a plot of the difference (in percent) - as a function of geopotential altitude (km). Note that there is a systematic difference between the two codes, with maximum difference of about 4.5e-3 percent. I can't comment on why this difference exists.

Also, while I have been writing MATLAB code for many years,I was not aware of the argument validation method you used: 
arguments
   ...
   ...
end

and I thank you for educating me.

Thanks for posting your nice work to GitHub!
Steve Auerbach

![Density Difference](https://user-images.githubusercontent.com/38922226/147713448-d11fc7f9-ecc2-483d-900e-d4df303d95fa.jpg)
